on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    
    - name: Use Node.js 24
      uses: actions/setup-node@v6
      with:
        node-version: 24
    
    - name: 🔨 Build Project
      run: |
        npm install
        npm run build
    
    - name: List output files
      run: find build/ -print
      
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.4.0
      with:
        server: ftp.samkirkland.com
        username: react-deploy-example@ftp-deploy-action-example-react.samkirkland.com
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: build/
